version: 2
updates:
  - package-ecosystem: npm
    target-branch: "dependecies/update"
    directory: "/"
    milestone: 6
    assignees:
      - "paolocattani"
    labels:
      - "npm"
      - "dependencies"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 20

  - package-ecosystem: npm
    target-branch: "dependecies/update"
    directory: "/server/"
    milestone: 6
    assignees:
      - "paolocattani"
    labels:
      - "npm server"
      - "dependencies"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    target-branch: "dependecies/update"
    directory: "/"
    milestone: 6
    assignees:
      - "paolocattani"
    labels:
      - "github actions"
      - "dependencies"
    schedule:
      interval: "daily"
