import { Stage1Row } from 'models';

export default ([
  {
    pair: {
      id: 13,
      rowNumber: 13,
      tId: 1,
      player1: {
        id: 18,
        alias: 'Melanie',
        name: 'Melanie',
        surname: '',
        label: 'Melanie',
        role: 'Attaccante',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      player2: {
        id: 11,
        alias: 'Niero',
        name: 'Niero',
        surname: '',
        label: 'Niero',
        role: 'Attaccante',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      alias: '',
      stage1Name: 'A',
      paid1: 'No',
      paid2: 'No',
      label: 'Melanie - Niero ( 13 )',
    },
    rowNumber: 5,
    col1: 0,
    col2: 0,
    col3: 3,
    col4: 0,
    col5: null,
    total: 3,
    place: 5,
    id: 'row-1-4',
  },
  {
    pair: {
      id: 10,
      rowNumber: 10,
      tId: 1,
      player1: {
        id: 5,
        alias: 'The Wall ',
        name: 'Dante',
        surname: 'Riello',
        label: 'The Wall ',
        role: 'Master',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      player2: {
        id: 19,
        alias: 'Luca',
        name: 'Luca',
        surname: '',
        label: 'Luca',
        role: 'Portiere',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      alias: 'PAlias10',
      stage1Name: 'A',
      paid1: 'No',
      paid2: 'No',
      label: 'PAlias10 ( 10 )',
    },
    rowNumber: 4,
    col1: 0,
    col2: 2,
    col3: 0,
    col4: null,
    col5: 3,
    total: 5,
    place: 3,
    id: 'row-1-3',
  },
  {
    pair: {
      id: 7,
      rowNumber: 7,
      tId: 1,
      player1: {
        id: 20,
        alias: 'Daniel',
        name: 'Daniel',
        surname: '',
        label: 'Daniel',
        role: 'Attaccante',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      player2: {
        id: 6,
        alias: 'Tope',
        name: 'Michele',
        surname: 'Maschio',
        label: 'Tope',
        role: 'Master',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      alias: '',
      stage1Name: 'A',
      paid1: 'No',
      paid2: 'No',
      label: 'Daniel - Tope ( 7 )',
    },
    rowNumber: 3,
    col1: 0,
    col2: 1,
    col3: null,
    col4: 3,
    col5: 0,
    total: 4,
    place: 4,
    id: 'row-1-2',
  },
  {
    pair: {
      id: 4,
      rowNumber: 4,
      tId: 1,
      player1: {
        id: 13,
        alias: 'Fabio',
        name: 'Fabio',
        surname: 'Zambello',
        label: 'Fabio',
        role: 'Attaccante',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      player2: {
        id: 13,
        alias: 'Fabio',
        name: 'Fabio',
        surname: 'Zambello',
        label: 'Fabio',
        role: 'Attaccante',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      alias: 'PAlias4',
      stage1Name: 'A',
      paid1: 'No',
      paid2: 'No',
      label: 'PAlias4 ( 4 )',
    },
    rowNumber: 2,
    col1: 1,
    col2: null,
    col3: 2,
    col4: 1,
    col5: 3,
    total: 7,
    place: 2,
    id: 'row-1-1',
  },
  {
    pair: {
      id: 1,
      rowNumber: 1,
      tId: 1,
      player1: {
        id: 1,
        alias: 'Messi',
        name: 'Andrea',
        surname: 'Messi',
        label: 'Messi',
        role: 'Master',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      player2: {
        id: 15,
        alias: 'Vanni',
        name: 'Vanni',
        surname: '',
        label: 'Vanni',
        role: 'Portiere',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      alias: '',
      stage1Name: 'A',
      paid1: 'No',
      paid2: 'No',
      label: 'Messi - Vanni ( 1 )',
    },
    rowNumber: 1,
    col1: null,
    col2: 2,
    col3: 3,
    col4: 3,
    col5: 3,
    total: 11,
    place: 1,
    id: 'row-1-0',
  },
  {
    pair: {
      id: 8,
      rowNumber: 8,
      tId: 1,
      player1: {
        id: 10,
        alias: 'Lorenzo',
        name: 'Lorenzo',
        surname: '',
        label: 'Lorenzo',
        role: 'Portiere',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      player2: {
        id: 1,
        alias: 'Messi',
        name: 'Andrea',
        surname: 'Messi',
        label: 'Messi',
        role: 'Master',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      alias: 'PAlias8',
      stage1Name: 'B',
      paid1: 'No',
      paid2: 'No',
      label: 'PAlias8 ( 8 )',
    },
    rowNumber: 3,
    col1: null,
    col2: null,
    col3: null,
    col4: null,
    total: null,
    place: 3,
    id: 'row-1-2',
  },
  {
    pair: {
      id: 5,
      rowNumber: 5,
      tId: 1,
      player1: {
        id: 1,
        alias: 'Messi',
        name: 'Andrea',
        surname: 'Messi',
        label: 'Messi',
        role: 'Master',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      player2: {
        id: 20,
        alias: 'Daniel',
        name: 'Daniel',
        surname: '',
        label: 'Daniel',
        role: 'Attaccante',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      alias: '',
      stage1Name: 'B',
      paid1: 'No',
      paid2: 'No',
      label: 'Messi - Daniel ( 5 )',
    },
    rowNumber: 2,
    col1: null,
    col2: null,
    col3: null,
    col4: null,
    total: null,
    place: 2,
    id: 'row-1-1',
  },
  {
    pair: {
      id: 2,
      rowNumber: 2,
      tId: 1,
      player1: {
        id: 10,
        alias: 'Lorenzo',
        name: 'Lorenzo',
        surname: '',
        label: 'Lorenzo',
        role: 'Portiere',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      player2: {
        id: 16,
        alias: 'Mirco',
        name: 'Mirco',
        surname: 'Dalan',
        label: 'Mirco',
        role: 'Portiere',
        match_played: '0',
        match_won: '0',
        total_score: 0,
        editable: true,
      },
      alias: 'PAlias2',
      stage1Name: 'B',
      paid1: 'No',
      paid2: 'No',
      label: 'PAlias2 ( 2 )',
    },
    rowNumber: 1,
    col1: null,
    col2: null,
    col3: null,
    col4: null,
    total: null,
    place: 1,
    id: 'row-1-0',
  },
] as unknown) as Stage1Row[];
