export default [
  {
    id: null,
    tId: 0,
    rowNumber: 0,
    player1: {
      id: null,
      name: '',
      surname: '',
      alias: '',
      label: '',
      role: 'Portiere',
      email: '',
      phone: '',
      match_played: 0,
      match_won: 0,
      total_score: 0,
      editable: false,
    },
    player2: {
      id: null,
      name: '',
      surname: '',
      alias: '',
      label: '',
      role: 'Portiere',
      email: '',
      phone: '',
      match_played: 0,
      match_won: 0,
      total_score: 0,
      editable: false,
    },
    alias: 'placeholder',
    stage1Name: '',
    placement: 0,
    paid1: false,
    paid2: false,
  },
  {
    id: 1,
    rowNumber: 1,
    tId: 1,
    player1: {
      id: 1,
      alias: 'Messi',
      name: 'Andrea',
      surname: 'Messi',
      label: 'Messi',
      role: 'Master',
      match_played: '0',
      match_won: '0',
      total_score: 0,
      editable: true,
    },
    player2: {
      id: 15,
      alias: 'Vanni',
      name: 'Vanni',
      surname: '',
      label: 'Vanni',
      role: 'Portiere',
      match_played: '0',
      match_won: '0',
      total_score: 0,
      editable: true,
    },
    alias: '',
    stage1Name: 'A',
    paid1: 'No',
    paid2: 'No',
    label: 'Messi - Vanni ( 1 )',
  },
  {
    id: 4,
    rowNumber: 4,
    tId: 1,
    player1: {
      id: 13,
      alias: 'Fabio',
      name: 'Fabio',
      surname: 'Zambello',
      label: 'Fabio',
      role: 'Attaccante',
      match_played: '0',
      match_won: '0',
      total_score: 0,
      editable: true,
    },
    player2: {
      id: 13,
      alias: 'Fabio',
      name: 'Fabio',
      surname: 'Zambello',
      label: 'Fabio',
      role: 'Attaccante',
      match_played: '0',
      match_won: '0',
      total_score: 0,
      editable: true,
    },
    alias: 'PAlias4',
    stage1Name: 'A',
    paid1: 'No',
    paid2: 'No',
    label: 'PAlias4 ( 4 )',
  },
  {
    id: 7,
    rowNumber: 7,
    tId: 1,
    player1: {
      id: 20,
      alias: 'Daniel',
      name: 'Daniel',
      surname: '',
      label: 'Daniel',
      role: 'Attaccante',
      match_played: '0',
      match_won: '0',
      total_score: 0,
      editable: true,
    },
    player2: {
      id: 6,
      alias: 'Tope',
      name: 'Michele',
      surname: 'Maschio',
      label: 'Tope',
      role: 'Master',
      match_played: '0',
      match_won: '0',
      total_score: 0,
      editable: true,
    },
    alias: '',
    stage1Name: 'A',
    paid1: 'No',
    paid2: 'No',
    label: 'Daniel - Tope ( 7 )',
  },
  {
    id: 10,
    rowNumber: 10,
    tId: 1,
    player1: {
      id: 5,
      alias: 'The Wall ',
      name: 'Dante',
      surname: 'Riello',
      label: 'The Wall ',
      role: 'Master',
      match_played: '0',
      match_won: '0',
      total_score: 0,
      editable: true,
    },
    player2: {
      id: 19,
      alias: 'Luca',
      name: 'Luca',
      surname: '',
      label: 'Luca',
      role: 'Portiere',
      match_played: '0',
      match_won: '0',
      total_score: 0,
      editable: true,
    },
    alias: 'PAlias10',
    stage1Name: 'A',
    paid1: 'No',
    paid2: 'No',
    label: 'PAlias10 ( 10 )',
  },
  {
    id: 13,
    rowNumber: 13,
    tId: 1,
    player1: {
      id: 18,
      alias: 'Melanie',
      name: 'Melanie',
      surname: '',
      label: 'Melanie',
      role: 'Attaccante',
      match_played: '0',
      match_won: '0',
      total_score: 0,
      editable: true,
    },
    player2: {
      id: 11,
      alias: 'Niero',
      name: 'Niero',
      surname: '',
      label: 'Niero',
      role: 'Attaccante',
      match_played: '0',
      match_won: '0',
      total_score: 0,
      editable: true,
    },
    alias: '',
    stage1Name: 'A',
    paid1: 'No',
    paid2: 'No',
    label: 'Melanie - Niero ( 13 )',
  },
];
