name: auto-merge

on:
  pull_request:
    types: [labeled]

jobs:
  auto-merge:
    # Runs only on PR with labeld 'dependencies' and 'npm' or 'npm server'
    if: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies')  && ( contains(github.event.pull_request.labels.*.name, 'npm server') || contains(github.event.pull_request.labels.*.name, 'npm') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}