name: Build/Test/Analyze
on:
  push:
    branches:
      - develop
      - graphql
  pull_request:
    branches:
      - develop

jobs:
  #-----------------------------------------
  # Build
  #-----------------------------------------
  build:
    runs-on: ubuntu-latest
    name: Build
    strategy:
      matrix:
        node-version: [ 10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      # Set up Node
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
      # Cache node-modules
      - name: Cache Node.js modules
        uses: actions/cache@v2.1.4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ env.cache-name }}-
            ${{ runner.os }}-npm-
            ${{ runner.os }}-
      # Add exect
      - name: Add exec to cli
        run: chmod +x cli/cli.sh
      # Build client
      - name: Build client
        run: ./cli/cli.sh build --frontend --analyze
      # Build server
      - name: Build server
        run: ./cli/cli.sh build --backend
      # Save build for later
      - name: Upload build
        uses: actions/upload-artifact@v2.2.2
        with:
          name: build-${{ matrix.node-version }}-frontend
          path: build
      - name: Upload build
        uses: actions/upload-artifact@v2.2.2
        with:
          name: build-${{ matrix.node-version }}-backend
          path: server/build
      # Save Eslint Analysis fron Sonar
      - name: Upload analysis
        uses: actions/upload-artifact@v2.2.2
        with:
          name: analysis-${{ matrix.node-version }}
          path: analysis
  #-----------------------------------------
  # Unit Test

  # Frontend
  unit-test-frontend:
    runs-on: ubuntu-latest
    needs: build
    name: Unit tests frontend
    steps:
      - uses: actions/checkout@v2
      # Restore cache
      - name: Restore cache Node.js modules
        uses: actions/cache@v2.1.4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ env.cache-name }}-
            ${{ runner.os }}-npm-
            ${{ runner.os }}-
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      # unit test
      - name: Unit Tests Frontend
        run: CI=true npm run CRA:test:coverage
      # Save coverage for sonar
      - name: Upload build
        uses: actions/upload-artifact@v2.2.2
        with:
          name: coverage-frontend
          path: coverage

  # Backend
  unit-test-backend:
    runs-on: ubuntu-latest
    needs: build
    name: Unit tests backend
    steps:
      - uses: actions/checkout@v2
      # Restore cache
      - name: Restore cache Node.js modules
        uses: actions/cache@v2.1.4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ env.cache-name }}-
            ${{ runner.os }}-npm-
            ${{ runner.os }}-
      # Install dependencies
      - name: Install dependencies
        run: cd server && npm ci
      # unit test 
      - name: Unit Tests Backend
        run: cd server && npm run test:unit:coverage
      # Save coverage for sonar
      - name: Upload build
        uses: actions/upload-artifact@v2.2.2
        with:
          name: coverage-backend
          path: server/coverage

  #-----------------------------------------
  # Code Quality ( Sonarcloud )
  #-----------------------------------------
  analyze:
    runs-on: ubuntu-latest
    needs: [build, unit-test-frontend, unit-test-backend]
    name: Code Quality
    steps:
        # Download Analysis, Coverage Frontend and Backend
        - name: Download analysis
          uses: actions/download-artifact@v2
          with:
            name: analysis-14.x
            path: analysis
        - name: Download coverage frontend
          uses: actions/download-artifact@v2
          with:
            name: coverage-frontend
            path: coverage
        - name: Download coverage backend
          uses: actions/download-artifact@v2
          with:
            name: coverage-backend
            path: server/coverage
        # https://github.com/marketplace/actions/sonarcloud-scan
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          with:
            projectBaseDir: /home/runner/work/calcetto/calcetto
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
